services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: src/UserService/Dockerfile

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
